definitions:
  define.AddFoodRequest:
    properties:
      foodicon:
        type: string
      foodname:
        type: string
      foodprocedure:
        type: string
      price:
        type: number
      remarks:
        type: string
      user_id:
        type: integer
      video:
        type: string
    type: object
  define.AddOrderRequest:
    properties:
      food:
        type: string
      num:
        type: integer
      remarks:
        type: string
      user:
        type: string
    type: object
  define.AddRoleRequest:
    properties:
      level:
        type: integer
      name:
        type: string
      remarks:
        type: string
    type: object
  define.AddUserRequest:
    properties:
      email:
        type: string
      password:
        type: string
      phone:
        type: string
      remarks:
        type: string
      role_id:
        type: integer
      sex:
        type: string
      status:
        type: boolean
      username:
        type: string
    type: object
  define.GetOrderListRequest:
    properties:
      keyword:
        type: string
      page:
        type: integer
      size:
        type: integer
      status:
        type: integer
    type: object
  define.GetRoleListRequest:
    properties:
      keyword:
        type: string
      page:
        type: integer
      size:
        type: integer
      status:
        type: integer
    type: object
  define.GetUserListRequest:
    properties:
      keyword:
        type: string
      page:
        type: integer
      size:
        type: integer
      status:
        type: integer
    type: object
  define.LoginPassWordRequest:
    properties:
      code:
        description: 登录验证码
        type: string
      password:
        description: 登录密码
        type: string
      username:
        description: 登录用户名
        type: string
    type: object
  define.UpdateFoodRequest:
    properties:
      foodicon:
        type: string
      foodname:
        type: string
      foodprocedure:
        type: string
      id:
        type: integer
      price:
        type: number
      remarks:
        type: string
      user_id:
        type: integer
      video:
        type: string
    type: object
  define.UpdateInfoType:
    properties:
      avatar:
        type: string
      id:
        type: integer
      sex:
        type: string
      username:
        type: string
    type: object
  define.UpdateRoleRequest:
    properties:
      id:
        type: integer
      level:
        type: integer
      name:
        type: string
      remarks:
        type: string
    type: object
  define.UpdateUserRequest:
    properties:
      email:
        type: string
      id:
        type: integer
      password:
        type: string
      phone:
        type: string
      remarks:
        type: string
      role_id:
        type: integer
      sex:
        type: string
      status:
        type: boolean
      username:
        type: string
    type: object
info:
  contact:
    name: Vulnerabilities_Server
    url: https://github.com/A7cc/Vulnerabilities_Server
  description: 这是一个用Golang写的食谱菜单管理系统靶场，该系统中存在多个安全漏洞，需要我们去探索和发现。\n\n该项目旨在帮助安全研究人员和爱好者了解和掌握关于Golang系统的渗透测试和代码审计知识。
  title: 食谱菜单管理系统靶场
  version: "1.0"
paths:
  /auth/login:
    post:
      parameters:
      - description: 登录信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/define.LoginPassWordRequest'
      responses: {}
      summary: 处理用户登录
      tags:
      - 公共方法
  /auth/loginout:
    get:
      responses: {}
      summary: 处理用户注销
      tags:
      - 公共方法
  /food/add:
    post:
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: 接收添加菜品表单数据
        in: body
        name: AddFoodRequest
        required: true
        schema:
          $ref: '#/definitions/define.AddFoodRequest'
      responses: {}
      summary: 添加菜品
      tags:
      - 鉴权接口-菜品相关方法
  /food/delete/{id}:
    delete:
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: 菜品ID
        in: path
        name: id
        required: true
        type: integer
      responses: {}
      summary: 删除菜品
      tags:
      - 鉴权接口-菜品相关方法
  /food/detail:
    get:
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: 获取菜品ID
        in: query
        name: id
        required: true
        type: integer
      responses: {}
      summary: 获取菜品详情信息
      tags:
      - 鉴权接口-菜品相关方法
  /food/get:
    get:
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - in: query
        name: keyword
        type: string
      - in: query
        name: page
        type: integer
      - in: query
        name: size
        type: integer
      - in: query
        name: status
        type: integer
      responses: {}
      summary: 获取菜品列表
      tags:
      - 鉴权接口-菜品相关方法
  /food/update:
    put:
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: 更新菜品信息
        in: body
        name: UpdateFoodRequest
        required: true
        schema:
          $ref: '#/definitions/define.UpdateFoodRequest'
      responses: {}
      summary: 更新菜品信息
      tags:
      - 鉴权接口-菜品相关方法
  /food/upfoodicon:
    post:
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: 更新菜品ICON
        in: formData
        name: file
        required: true
        type: file
      responses: {}
      summary: 更新菜品ICON
      tags:
      - 鉴权接口-菜品相关方法
  /food/upfoodvideo:
    post:
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: 更新菜品视频
        in: formData
        name: file
        required: true
        type: file
      responses: {}
      summary: 更新菜品Video
      tags:
      - 鉴权接口-菜品相关方法
  /home/get:
    get:
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      responses: {}
      summary: 获取系统数据信息
      tags:
      - 鉴权接口-首页设置方法
  /home/getsentence:
    get:
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: 获取每日金句的url
        in: query
        name: url
        required: true
        type: string
      responses: {}
      summary: 获取每日金句
      tags:
      - 鉴权接口-首页设置方法
  /home/updateInfo:
    put:
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: 用户自己更新个人信息参数
        in: body
        name: UpdateInfoType
        required: true
        schema:
          $ref: '#/definitions/define.UpdateInfoType'
      responses: {}
      summary: 用户自己更新个人信息
      tags:
      - 鉴权接口-首页设置方法
  /home/updatePwd:
    put:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: 用户自己更新密码和UID
        in: body
        name: newpwdinfo
        required: true
        schema:
          type: string
      responses: {}
      summary: 更改个人密码
      tags:
      - 鉴权接口-首页设置方法
  /home/upuseravatar:
    post:
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: 更新头像
        in: formData
        name: file
        required: true
        type: file
      responses: {}
      summary: 更新头像
      tags:
      - 鉴权接口-首页设置方法
  /order/add:
    post:
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: 添加订单信息
        in: body
        name: AddOrderRequest
        required: true
        schema:
          $ref: '#/definitions/define.AddOrderRequest'
      responses: {}
      summary: 新增订单信息
      tags:
      - 鉴权接口-订单相关方法
  /order/delete/{id}:
    delete:
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: 删除订单ID
        in: path
        name: id
        required: true
        type: integer
      responses: {}
      summary: 删除订单信息
      tags:
      - 鉴权接口-订单相关方法
  /order/detail:
    get:
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: 获取订单ID
        in: query
        name: id
        required: true
        type: string
      responses: {}
      summary: 根据ID获取订单信息
      tags:
      - 鉴权接口-订单相关方法
  /order/get:
    get:
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: 获取订单查询参数
        in: body
        name: GetOrderListRequest
        required: true
        schema:
          $ref: '#/definitions/define.GetOrderListRequest'
      responses: {}
      summary: 获取订单列表
      tags:
      - 鉴权接口-订单相关方法
  /role/add:
    post:
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: 添加角色信息
        in: body
        name: AddRoleRequest
        required: true
        schema:
          $ref: '#/definitions/define.AddRoleRequest'
      responses: {}
      summary: 新增角色信息
      tags:
      - 鉴权接口-角色相关方法
  /role/delete/{id}:
    delete:
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: 删除角色ID
        in: path
        name: id
        required: true
        type: integer
      responses: {}
      summary: 删除角色信息
      tags:
      - 鉴权接口-角色相关方法
  /role/detail:
    get:
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: 获取角色ID
        in: query
        name: id
        required: true
        type: integer
      responses: {}
      summary: 根据ID获取角色信息
      tags:
      - 鉴权接口-角色相关方法
  /role/get:
    get:
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: 获取角色查询参数
        in: body
        name: GetRoleListRequest
        required: true
        schema:
          $ref: '#/definitions/define.GetRoleListRequest'
      responses: {}
      summary: 获取角色列表信息
      tags:
      - 鉴权接口-角色相关方法
  /role/update:
    put:
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: 更新角色信息参数
        in: body
        name: UpdateRoleRequest
        required: true
        schema:
          $ref: '#/definitions/define.UpdateRoleRequest'
      responses: {}
      summary: 修改角色信息
      tags:
      - 鉴权接口-角色相关方法
  /settings/backupsdb:
    get:
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      responses: {}
      summary: 备份数据库
      tags:
      - 鉴权接口-系统设置相关方法
  /settings/deletedb:
    post:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: 删除数据库备份文件
        in: body
        name: dbfile
        required: true
        schema:
          type: string
      responses: {}
      summary: 删除数据库
      tags:
      - 鉴权接口-系统设置相关方法
  /settings/downdb:
    post:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: 下载数据库备份文件
        in: body
        name: dbfile
        required: true
        schema:
          type: string
      responses: {}
      summary: 数据库下载
      tags:
      - 鉴权接口-系统设置相关方法
  /settings/getdb:
    post:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: 数据库备份目录
        in: body
        name: dir
        required: true
        schema:
          type: string
      responses: {}
      summary: 获取数据库列表
      tags:
      - 鉴权接口-系统设置相关方法
  /settings/ping:
    post:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: IP地址
        in: body
        name: addre
        required: true
        schema:
          type: string
      responses: {}
      summary: 测试连通性
      tags:
      - 鉴权接口-系统设置相关方法
  /user/add:
    post:
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: 添加用户信息
        in: body
        name: AddUserRequest
        required: true
        schema:
          $ref: '#/definitions/define.AddUserRequest'
      responses: {}
      summary: 新增用户信息
      tags:
      - 鉴权接口-用户相关方法
  /user/delete/{id}:
    delete:
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: 删除用户ID
        in: path
        name: id
        required: true
        type: integer
      responses: {}
      summary: 删除用户信息
      tags:
      - 鉴权接口-用户相关方法
  /user/detail:
    get:
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: 获取用户ID
        in: query
        name: id
        required: true
        type: integer
      responses: {}
      summary: 根据ID获取用户信息
      tags:
      - 鉴权接口-用户相关方法
  /user/get:
    get:
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: 获取用户查询参数
        in: body
        name: GetUserListRequest
        required: true
        schema:
          $ref: '#/definitions/define.GetUserListRequest'
      responses: {}
      summary: 获取用户列表信息
      tags:
      - 鉴权接口-用户相关方法
  /user/update:
    put:
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: 更新用户信息参数
        in: body
        name: UpdateUserRequest
        required: true
        schema:
          $ref: '#/definitions/define.UpdateUserRequest'
      responses: {}
      summary: 修改用户信息
      tags:
      - 鉴权接口-用户相关方法
swagger: "2.0"
